spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      oss:
        bucket: gulimall-38756175

  application:
    name: gulimall-third-party

server:
  port: 30000
